# Generated by Django 4.0.5 on 2022-07-07 18:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateField(auto_created=True, default=datetime.date(2022, 7, 7))),
                ('created_at', models.DateField(auto_created=True, default=datetime.date(2022, 7, 7))),
                ('title', models.CharField(max_length=200)),
                ('Desc', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
        ),
    ]
