# Generated by Django 4.0.5 on 2022-07-07 16:23

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='completed',
        ),
        migrations.RemoveField(
            model_name='task',
            name='id',
        ),
        migrations.RemoveField(
            model_name='task',
            name='title',
        ),
        migrations.AddField(
            model_name='task',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 7, 7)),
        ),
        migrations.AddField(
            model_name='task',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('da6c15df-7f2f-4dc7-8647-72b7844e3f00'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='task',
            name='updated_at',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 7, 7)),
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('task_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='todo.task')),
                ('title', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            bases=('todo.task',),
        ),
    ]
