# Generated by Django 4.0.5 on 2022-07-07 18:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task2',
            name='Desc',
        ),
    ]
