# Generated by Django 4.0.5 on 2022-07-07 16:25

import datetime
from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0002_remove_task_completed_remove_task_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='task_ptr',
        ),
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 7, 7)),
        ),
        migrations.AddField(
            model_name='todo',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('e330dd9a-c8d1-4dbc-a784-15bd9845e883'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AddField(
            model_name='todo',
            name='updated_at',
            field=models.DateField(auto_created=True, default=datetime.date(2022, 7, 7)),
        ),
        migrations.DeleteModel(
            name='Task',
        ),
    ]
