# Generated by Django 4.0.5 on 2022-07-07 18:09

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_remove_task2_id_task2_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('5e13302a-ddc2-4ac5-8762-cde7ce22be0e'), editable=False, primary_key=True, serialize=False),
        ),
    ]
