# Generated by Django 4.0.5 on 2022-07-07 18:11

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0004_alter_task2_uid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task2',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('f95b97e2-d6e8-410a-9707-fbd1a11fa353'), editable=False, primary_key=True, serialize=False),
        ),
    ]
