# Generated by Django 4.0.5 on 2022-07-07 18:12

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0006_alter_task2_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='task2',
            name='Desc',
            field=models.CharField(default=django.utils.timezone.now, max_length=200),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task2',
            name='uid',
            field=models.UUIDField(default=uuid.UUID('75317bf8-4685-4e3d-9609-07865c1e2a89'), editable=False, primary_key=True, serialize=False),
        ),
    ]
