# Generated by Django 4.0.5 on 2022-07-12 04:53

import datetime
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0007_task2_desc_alter_task2_uid'),
    ]

    operations = [
        migrations.CreateModel(
            name='timeTodo',
            fields=[
                ('updated_at', models.DateField(auto_created=True, default=datetime.date(2022, 7, 12))),
                ('created_at', models.DateField(auto_created=True, default=datetime.date(2022, 7, 12))),
                ('uid', models.UUIDField(default=uuid.UUID('c494a11e-ab26-4fdb-a1c6-2e6d3acf3763'), editable=False, primary_key=True, serialize=False)),
                ('timing', models.DateField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Todo',
            fields=[
                ('updated_at', models.DateField(auto_created=True, default=datetime.date(2022, 7, 12))),
                ('created_at', models.DateField(auto_created=True, default=datetime.date(2022, 7, 12))),
                ('uid', models.UUIDField(default=uuid.UUID('c494a11e-ab26-4fdb-a1c6-2e6d3acf3763'), editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('Desc', models.CharField(max_length=200)),
                ('completed', models.BooleanField(blank=True, default=False, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.DeleteModel(
            name='Task2',
        ),
        migrations.AddField(
            model_name='timetodo',
            name='todo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='todo.todo'),
        ),
    ]
